on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev
          
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: x64
      - name: Create Output Directory
        run: mkdir -p dist
      - name: Compile
        run: gcc -Wall -o dist/cwup cwup.c -lX11
      - name: Upload
        uses: "actions/upload-artifact@v5"
        with:
          name: CWUP-linux-distruvution
          path: dist/cwup
