on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: latest
          platform: x64
      - name: Compile
        run: gcc -Wall -o cwup cwup.c -lX11
